### ISSUE TITLE
README

### ISSUE THREAD

**Issue by unicodeveloper** [andela-doladosu/ngemoji#2]
From the readme, i discovered that for every request I have to pass in username and password with token. Thats very very wrong.

Why  will I have to do that? Then, what's the use of the token generated?

Once I have been registered, When I login with the username and password, it should generate a token that I should just use for subsequent requests. 

I dont need no username and password, only the token for all the other requests that needs authorization. Please Fix!

**Comment by dara-tobi** [comment]
I actually already fixed this issue. I consulted with Bendozy on it and he said exactly what you just said. I fixed it thereafter, but didn't update the readme as regards it. I''m updating it now.
